package bilibili.majiang.community.mapper;

import bilibili.majiang.community.model.GithubUser;
import bilibili.majiang.community.model.GithubUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GithubUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    long countByExample(GithubUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int deleteByExample(GithubUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int insert(GithubUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int insertSelective(GithubUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    List<GithubUser> selectByExample(GithubUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    GithubUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") GithubUser record, @Param("example") GithubUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int updateByExample(@Param("record") GithubUser record, @Param("example") GithubUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int updateByPrimaryKeySelective(GithubUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUBUSER
     *
     * @mbg.generated Thu Apr 01 17:34:30 CST 2021
     */
    int updateByPrimaryKey(GithubUser record);
}